EDIS/EDIS/Areas/Admin/Controllers/InvoiceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EDIS.Data;
using EDIS.Models.RepairModels;
using Microsoft.AspNetCore.Authorization;
using EDIS.Areas.Admin.Models;
using EDIS.Models.KeepModels;
using EDIS.Repositories;
using EDIS.Models.Identity;
using System.IO;
using ClosedXML.Excel;
using EDIS.Models;

namespace EDIS.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class InvoiceController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IRepository<AppUserModel, int> _userRepo;

        public InvoiceController(ApplicationDbContext context,
                                 IRepository<AppUserModel, int> userRepo)
        {
            _context = context;
            _userRepo = userRepo;
        }

        // GET: Admin/Invoice
        public async Task<IActionResult> Index()
        {
            return View();
        }

        // POST: Admin/Invoice
        [HttpPost]
        public async Task<IActionResult> Index(QryInvoiceVModel qdata)
        {
            string qryDocType = qdata.qtyDOCTYPE;

            List<RepairCostModel> rv = new List<RepairCostModel>();
            List<KeepCostModel> kv = new List<KeepCostModel>();
            if (qryDocType == "請修")
            {
                rv = GetRepInvoiceList(qdata);
                return PartialView("RepInvoiceList", rv);
            }
            else
            {
                kv = GetKeepInvoiceList(qdata);
                return PartialView("KeepInvoiceList", kv);
            }
        }

        // GET: Admin/Invoice/RepCostEdit/5
        public IActionResult RepCostEdit(string docid, string seqno)
        {
            RepairCostModel repairCost = _context.RepairCosts.Include(rc => rc.TicketDtl)
                                                             .SingleOrDefault(rc => rc.DocId == docid && rc.SeqNo == Convert.ToInt32(seqno));

            if (repairCost.StockType == "0")
                ViewData["StockType"] = "庫存";
            else if (repairCost.StockType == "2")
                ViewData["StockType"] = "發票(含收據)";
            else if (repairCost.StockType == "4")
                ViewData["StockType"] = "零用金";
            else
                ViewData["StockType"] = "簽單";

            return View(repairCost);
        }

        // POST: Admin/Invoice/RepCostEdit/5
        [HttpPost]
        public IActionResult RepCostEdit(RepairCostModel repairCost)
        {
            var ur = _userRepo.Find(u => u.UserName == this.User.Identity.Name).FirstOrDefault();
            if (repairCost.SignNo != null)
            {
                repairCost.SignNo = repairCost.SignNo.ToUpper();
            }
            if (repairCost.StockType == "3")
            {
                ModelState.Remove("TicketDtl.SeqNo");
            }
            if (ModelState.IsValid)
            {
                repairCost.Rtp = ur.Id;
                repairCost.Rtt = DateTime.Now;
                _context.Entry(repairCost).State = EntityState.Modified;
                _context.SaveChanges();

                RepairDtlModel dtl = _context.RepairDtls.Where(d => d.DocId == repairCost.DocId)
                                                        .FirstOrDefault();
                if (dtl != null)
                {
                    dtl.Cost = _context.RepairCosts.Where(k => k.DocId == repairCost.DocId)
                                                   .Select(k => k.TotalCost)
                                                   .DefaultIfEmpty(0).Sum();
                    _context.Entry(dtl).State = EntityState.Modified;
                    _context.SaveChanges();
                }

                return new JsonResult(repairCost)
                {
                    Value = new { success = true, error = "" }
                };
            }
            else
            {
                string msg = "";
                foreach (var error in ViewData.ModelState.Values.SelectMany(modelState => modelState.Errors))
                {
                    msg += error.ErrorMessage + Environment.NewLine;
                }
                throw new Exception(msg);
            }
        }

        // GET: Admin/Invoice/KeepCostEdit/5
        public IActionResult KeepCostEdit(string docid, string seqno)
        {
            KeepCostModel keepCost = _context.KeepCosts.Include(rc => rc.TicketDtl)
                                                       .SingleOrDefault(rc => rc.DocId == docid && rc.SeqNo == Convert.ToInt32(seqno));

            if (keepCost.StockType == "0")
                ViewData["StockType"] = "庫存";
            else if (keepCost.StockType == "2")
                ViewData["StockType"] = "發票(含收據)";
            else if (keepCost.StockType == "4")
                ViewData["StockType"] = "零用金";
            else
                ViewData["StockType"] = "簽單";

            return View(keepCost);
        }

        // POST: Admin/Invoice/KeepCostEdit/5
        [HttpPost]
        public IActionResult KeepCostEdit(KeepCostModel keepCost)
        {
            var ur = _userRepo.Find(u => u.UserName == this.User.Identity.Name).FirstOrDefault();
            if (keepCost.SignNo != null)
            {
                keepCost.SignNo = keepCost.SignNo.ToUpper();
            }
            if (keepCost.StockType == "3")
            {
                ModelState.Remove("TicketDtl.SeqNo");
            }
            if (ModelState.IsValid)
            {
                keepCost.Rtp = ur.Id;
                keepCost.Rtt = DateTime.Now;
                _context.Entry(keepCost).State = EntityState.Modified;
                _context.SaveChanges();

                KeepDtlModel dtl = _context.KeepDtls.Where(d => d.DocId == keepCost.DocId)
                                                    .FirstOrDefault();
                if (dtl != null)
                {
                    dtl.Cost = _context.KeepCosts.Where(k => k.DocId == keepCost.DocId)
                                                 .Select(k => k.TotalCost)
                                                 .DefaultIfEmpty(0).Sum();
                    _context.Entry(dtl).State = EntityState.Modified;
                    _context.SaveChanges();
                }

                return new JsonResult(keepCost)
                {
                    Value = new { success = true, error = "" }
                };
            }
            else
            {
                string msg = "";
                foreach (var error in ViewData.ModelState.Values.SelectMany(modelState => modelState.Errors))
                {
                    msg += error.ErrorMessage + Environment.NewLine;
                }
                throw new Exception(msg);
            }
        }

        // GET: Admin/Invoice/RepDelete/5
        public async Task<IActionResult> RepDelete(string docId, int? seqNo)
        {
            if (docId == null || seqNo == null)
            {
                return NotFound();
            }

            var repairCostModel = await _context.RepairCosts.FindAsync(docId, seqNo);
            if (repairCostModel == null)
            {
                return NotFound();
            }

            return View(repairCostModel);
        }

        // POST: Admin/Invoice/RepDelete/5
        [HttpPost]
        [ActionName("RepDelete")]
        public ActionResult RepDeleteConfirm(string docid, int? seqno)
        {
            try
            {
                RepairCostModel repairCost = _context.RepairCosts.Find(docid, Convert.ToInt32(seqno));
                _context.RepairCosts.Remove(repairCost);
                _context.SaveChanges();
                //
                RepairDtlModel dtl = _context.RepairDtls.Where(d => d.DocId == repairCost.DocId)
                                                        .FirstOrDefault();
                if (dtl != null)
                {
                    dtl.Cost = _context.RepairCosts.Where(k => k.DocId == repairCost.DocId)
                                                   .Select(k => k.TotalCost)
                                                   .DefaultIfEmpty(0).Sum();
                    _context.Entry(dtl).State = EntityState.Modified;
                    _context.SaveChanges();
                }
                return new JsonResult(repairCost)
                {
                    Value = new { success = true, error = "" }
                };
            }
            catch (Exception e)
            {
                throw new Exception(e.Message);
            }
        }

        // GET: Admin/Invoice/KeepDelete/5
        public async Task<IActionResult> KeepDelete(string docId, int? seqNo)
        {
            if (docId == null || seqNo == null)
            {
                return NotFound();
            }
            var keepCostModel = await _context.KeepCosts.FindAsync(docId, seqNo);
            if (keepCostModel == null)
            {
                return NotFound();
            }

            return View(keepCostModel);
        }

        // POST: Admin/Invoice/KeepDelete/5
        [HttpPost]
        [ActionName("KeepDelete")]
        public ActionResult KeepDeleteConfirm(string docid, int? seqno)
        {
            try
            {
                KeepCostModel keepCost = _context.KeepCosts.Find(docid, Convert.ToInt32(seqno));
                _context.KeepCosts.Remove(keepCost);
                _context.SaveChanges();
                //
                KeepDtlModel dtl = _context.KeepDtls.Where(d => d.DocId == keepCost.DocId)
                                                    .FirstOrDefault();
                if (dtl != null)
                {
                    dtl.Cost = _context.KeepCosts.Where(k => k.DocId == keepCost.DocId)
                                                 .Select(k => k.TotalCost)

EDIS/EDIS/Controllers/TicketController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EDIS.Data;
using EDIS.Models.RepairModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace EDIS.Controllers
{
    [Authorize]
    public class TicketController : Controller
    {
        private readonly ApplicationDbContext _context;

        public TicketController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public string GetTicketSeq()
        {
            string result = "";
            int seq = 0;
            string yyymm = Convert.ToString((DateTime.Now.Year - 1911) * 100 + DateTime.Now.Month);
            int cnt = _context.Ticket_seq_tmps.Where(t => t.YYYMM == yyymm).Count();
            Ticket_seq_tmpModel tmp;
            if (cnt > 0)
            {
                tmp = _context.Ticket_seq_tmps.Find(yyymm);
                seq = Convert.ToInt32(tmp.TICKET_SEQ) + 1;
                result = Convert.ToString(seq);
                tmp.TICKET_SEQ = Convert.ToString(seq);
                _context.Entry(tmp).State = EntityState.Modified;
            }
            else
            {
                tmp = new Ticket_seq_tmpModel();
                seq = Convert.ToInt32(yyymm) * 1000 + 1;
                tmp.YYYMM = Convert.ToString(yyymm);
                tmp.TICKET_SEQ = Convert.ToString(seq);
                result = Convert.ToString(seq);
                _context.Ticket_seq_tmps.Add(tmp);
            }
            _context.SaveChanges();

            return result;
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _context.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EDIS/EDIS/Areas/Admin/Views/Invoice/KeepCostEdit.cshtml
@model EDIS.Models.KeepModels.KeepCostModel
@{
    Layout = "~/Views/Shared/_PassedLayout.cshtml";
}

<script>
    $(function () {

        /* Default setting for the view. */
        $("#Price").attr('readonly', true);
        $("#TotalCost").attr('readonly', true);
        $('#PartName').attr("readonly", false);
        $('#Price').attr("readonly", false);
        $('#btnQtyStok').hide();
        $("#pnlSIGN").hide();
        $("#pnlACCDATE").show();
        $("#CVendor").show();
        $("#pnlTICKET").show();
        $('label[for="AccountDate"]').text("發票日期");

        var stockType = $('#StockType').val();
        //console.log(stockType);
        /* According stock type to change labels and input textboxs. */
        if (stockType === "2" || stockType === "4") {             // 點選"發票" 或 "零用金"
            $('#btnQtyStok').hide();
            $("#SignNo").val('');
            $("#pnlSIGN").hide();
            $("#pnlACCDATE").show();
            $("#CVendor").show();
            $("#pnlTICKET").show();
            $('label[for="AccountDate"]').text("發票日期");
            $('#TicketDtl_TicketDtlNo').attr("required", "required");
            $('#AccountDate').attr("required", "required");
        }
        else {        // 點選"簽單"
            $("#TicketDtl_TicketDtlNo").val('');
            $("#pnlTICKET").hide();
            $("#pnlACCDATE").show();
            $("#pnlSIGN").show();
            $('label[for="AccountDate"]').text("簽單日期");
            $('input:radio[name="IsPetty"]').prop("disabled", true);
        }

        /* Auto calculate total price when input price or qty. */
        $('#Price').change(function () {
            var v1 = $(this).val();
            var v2 = $('#Qty').val();
            if (v1 !== null && v2 !== null) {
                $('#TotalCost').val(v1 * v2);
            }
        });
        $('#Qty').change(function () {
            var v1 = $(this).val();
            var v2 = $('#Price').val();
            if (v1 !== null && v2 !== null) {
                $('#TotalCost').val(v1 * v2);
            }
        });

        var url = '@Url.Action("GetTicketSeq", "Ticket")';
        /* Get ticket seq. */
        $("#btnGETSEQ").click(function () {
            $.ajax({
                url: url,
                type: "POST",
                async: true,
                success: function (data) {
                    //console.log(data); // For Debug
                    $("#TicketDtl_TicketDtlNo").val("AA" + data);
                }
            });
        });

        $("#modalVENDOR").on("hidden.bs.modal", function () {
            var vendorName = $("#Vno option:selected").text();
            var vendorId = $("#Vno option:selected").val();

            /* includes is not support in IE, so need to user indexOf. */
            if ($("#Vno option:selected").text() == "請選擇" || $("#Vno option:selected").text() == "查無廠商" ||
                $("#Vno option:selected").text().indexOf("請選擇廠商") != -1) {
                $("#VendorName").val("");
                $("#VendorId").val("");
            }
            else {
                $("#VendorName").val(vendorName);
                $("#VendorId").val(vendorId);
            }
        });

    });
    var onFailed = function (data) {
        alert(data.responseText);
        $.Toast.hideToast();
    };
    function onSuccess() {
        alert("修改成功!");
        $.Toast.hideToast();
        if (window.opener != null) {
            window.opener.location = "javascript:ReSubmit();";
            window.close();
        }
    }
</script>

<h3>費用明細</h3>
<h4>修改</h4>
<hr />
<form asp-action="KeepCostEdit" asp-controller="Invoice" asp-area="Admin" data-ajax="true" data-ajax-method="POST" id="keepCostEditForm"
      data-ajax-begin="$.Toast.showToast({
          'title':'作業進行中，請稍待...',
          'icon':'loading',
          'duration':0
          })"
      data-ajax-failure="onFailed"
      data-ajax-success="onSuccess()">

    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.DocId, new { id = "costDocId" })
    @Html.HiddenFor(model => model.SeqNo, new { id = "costSeqNo" })
    @Html.HiddenFor(model => model.StockType)
    @Html.HiddenFor(model => model.TicketDtl.SeqNo)

    <div class="container">
        <div class="row">
            <div class="form-inline">
                <label asp-for="StockType" class="control-title"></label>
                <span>@ViewData["StockType"]</span>
            </div>
        </div>
        <div class="row">
            @Html.HiddenFor(model => model.VendorId)
            <div class=form-inline>
                <div class="form-group">
                    <label asp-for="VendorName" class="control-title"></label>
                    <input asp-for="VendorName" class="form-control" readonly placeholder="請於右方按鈕選擇廠商" />
                    <input type="button" value="選擇" class="btn btn-default" data-toggle="modal" data-target="#modalVENDOR" />
                    <span asp-validation-for="VendorName" class="text-danger"></span>
                </div>
            </div>
        </div>
        <div class="row">
            @Html.HiddenFor(model => model.PartNo)
            <div class=form-inline>
                <div class="form-group">
                    <label asp-for="PartName" class="control-title"></label>
                    <input asp-for="PartName" class="form-control" />
                    <span style="color: #ff9c00;">*</span>
                    <span asp-validation-for="PartName" class="text-danger"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class=form-inline>
                <div class="form-group">
                    <label asp-for="Standard" class="control-title"></label>
                    <input asp-for="Standard" class="form-control" />
                    <span asp-validation-for="Standard" class="text-danger"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class=form-inline>
                <div class="form-group">
                    <label asp-for="Unite" class="control-title"></label>
                    <input asp-for="Unite" class="form-control-s" />
                    <span style="color: #ff9c00;">*</span>
                    <span asp-validation-for="Unite" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Price" class="control-title"></label>
                    <input asp-for="Price" class="form-control-s" />
                    <span asp-validation-for="Price" class="text-danger"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class=form-inline>
                <div class="form-group">
                    <label asp-for="Qty" class="control-title"></label>
                    <input asp-for="Qty" class="form-control-s" />
                    <span>&nbsp;</span>
                    <span asp-validation-for="Qty" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="TotalCost" class="control-title"></label>
                    <input asp-for="TotalCost" class="form-control-s" />
                    <span asp-validation-for="TotalCost" class="text-danger"></span>
                </div>
            </div>
        </div>
        <div id="pnlSIGN" class="row">
            <div class=form-inline>
                <div class="form-group">
                    <label asp-for="SignNo" class="control-title"></label>
                    <input asp-for="SignNo" class="form-control" style="text-transform:uppercase;" />
                    <span asp-validation-for="SignNo" class="text-danger"></span>
                </div>
            </div>
        </div>
        <div id="pnlACCDATE" class="row">
            <div class=form-inline>
                <div class="form-group">
                    <label asp-for="AccountDate" class="control-title"></label>
                    <input asp-for="AccountDate" class="form-control" />
                    <span asp-validation-for="AccountDate" class="text-danger"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div style="padding-left: 115px">
                <input type="submit" value="儲存" class="btn btn-default" />
            </div>
        </div>

    </div>
</form>

<!-- 廠商 Modal -->
<div id="modalVENDOR" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content" style="background-color: #1D3C4C">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" style="color:#fff">&times;</button>
                <h4 class="modal-title">選擇廠商</h4>
            </div>
            <div id="pnlSELECTVENDOR" class="modal-body">
                @await Component.InvokeAsync("QryVendor")
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">儲存</button>
            </div>
        </div>
    </div>
</div>

EDIS/EDIS/Areas/Admin/Views/Invoice/RepCostEdit.cshtml
@model EDIS.Models.RepairModels.RepairCostModel
@{
    Layout = "~/Views/Shared/_PassedLayout.cshtml";
}

<script>
    $(function () {

        /* Default setting for the view. */
        $("#Price").attr('readonly', true);
        $("#TotalCost").attr('readonly', true);
        $('#PartName').attr("readonly", false);
        $('#Price').attr("readonly", false);
        $('#btnQtyStok').hide();
        $("#pnlSIGN").hide();
        $("#pnlACCDATE").show();
        $("#CVendor").show();
        $("#pnlTICKET").show();
        $('label[for="AccountDate"]').text("發票日期");

        var stockType = $('#StockType').val();
        //console.log(stockType);
        /* According stock type to change labels and input textboxs. */
        if (stockType === "2" || stockType === "4") {             // 點選"發票" 或 "零用金"
            $('#btnQtyStok').hide();
            $("#SignNo").val('');
            $("#pnlSIGN").hide();
            $("#pnlACCDATE").show();
            $("#CVendor").show();
            $("#pnlTICKET").show();
            $('label[for="AccountDate"]').text("發票日期");
            $('#TicketDtl_TicketDtlNo').attr("required", "required");
            $('#AccountDate').attr("required", "required");
        }
        else {        // 點選"簽單"
            $("#TicketDtl_TicketDtlNo").val('');
            $("#pnlTICKET").hide();
            $("#pnlACCDATE").show();
            $("#pnlSIGN").show();
            $('label[for="AccountDate"]').text("簽單日期");
            $('input:radio[name="IsPetty"]').prop("disabled", true);
        }

        /* Auto calculate total price when input price or qty. */
        $('#Price').change(function () {
            var v1 = $(this).val();
            var v2 = $('#Qty').val();
            if (v1 !== null && v2 !== null) {
                $('#TotalCost').val(v1 * v2);
            }
        });
        $('#Qty').change(function () {
            var v1 = $(this).val();
            var v2 = $('#Price').val();
            if (v1 !== null && v2 !== null) {
                $('#TotalCost').val(v1 * v2);
            }
        });

        var url = '@Url.Action("GetTicketSeq", "Ticket")';
        /* Get ticket seq. */
        $("#btnGETSEQ").click(function () {
            $.ajax({
                url: url,
                type: "POST",
                async: true,
                success: function (data) {
                    //console.log(data); // For Debug
                    $("#TicketDtl_TicketDtlNo").val("AA" + data);
                }
            });
        });

        $("#modalVENDOR").on("hidden.bs.modal", function () {
            var vendorName = $("#Vno option:selected").text();
            var vendorId = $("#Vno option:selected").val();

            /* includes is not support in IE, so need to user indexOf. */
            if ($("#Vno option:selected").text() == "請選擇" || $("#Vno option:selected").text() == "查無廠商" ||
                $("#Vno option:selected").text().indexOf("請選擇廠商") != -1) {
                $("#VendorName").val("");
                $("#VendorId").val("");
            }
            else {
                $("#VendorName").val(vendorName);
                $("#VendorId").val(vendorId);
            }
        });

    });
    var onFailed = function (data) {
        alert(data.responseText);
        $.Toast.hideToast();
    };
    function onSuccess() {
        alert("修改成功!");
        $.Toast.hideToast();
        if (window.opener != null) {
            window.opener.location = "javascript:ReSubmit();";
            window.close();
        }
    }
</script>

<h3>費用明細</h3>
<h4>修改</h4>
<hr />
<form asp-action="RepCostEdit" asp-controller="Invoice" asp-area="Admin" data-ajax="true" data-ajax-method="POST" id="repCostEditForm"
      data-ajax-begin="$.Toast.showToast({
          'title':'作業進行中，請稍待...',
          'icon':'loading',
          'duration':0
          })"
      data-ajax-failure="onFailed"
      data-ajax-success="onSuccess()">

    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.DocId, new { id = "costDocId" })
    @Html.HiddenFor(model => model.SeqNo, new { id = "costSeqNo" })
    @Html.HiddenFor(model => model.StockType)
    @Html.HiddenFor(model => model.TicketDtl.SeqNo)

    <div class="container">
        <div class="row">
            <div class="form-inline">
                <label asp-for="StockType" class="control-title"></label>
                <span>@ViewData["StockType"]</span>
            </div>
        </div>
        <div class="row">
            @Html.HiddenFor(model => model.VendorId)
            <div class=form-inline>
                <div class="form-group">
                    <label asp-for="VendorName" class="control-title"></label>
                    <input asp-for="VendorName" class="form-control" readonly placeholder="請於右方按鈕選擇廠商" />
                    <input type="button" value="選擇" class="btn btn-default" data-toggle="modal" data-target="#modalVENDOR" />
                    <span asp-validation-for="VendorName" class="text-danger"></span>
                </div>
            </div>
        </div>
        <div class="row">
            @Html.HiddenFor(model => model.PartNo)
            <div class=form-inline>
                <div class="form-group">
                    <label asp-for="PartName" class="control-title"></label>
                    <input asp-for="PartName" class="form-control" />
                    <span style="color: #ff9c00;">*</span>
                    <span asp-validation-for="PartName" class="text-danger"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class=form-inline>
                <div class="form-group">
                    <label asp-for="Standard" class="control-title"></label>
                    <input asp-for="Standard" class="form-control" />
                    <span asp-validation-for="Standard" class="text-danger"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class=form-inline>
                <div class="form-group">
                    <label asp-for="Unite" class="control-title"></label>
                    <input asp-for="Unite" class="form-control-s" />
                    <span style="color: #ff9c00;">*</span>
                    <span asp-validation-for="Unite" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Price" class="control-title"></label>
                    <input asp-for="Price" class="form-control-s" />
                    <span asp-validation-for="Price" class="text-danger"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class=form-inline>
                <div class="form-group">
                    <label asp-for="Qty" class="control-title"></label>
                    <input asp-for="Qty" class="form-control-s" />
                    <span>&nbsp;</span>
                    <span asp-validation-for="Qty" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="TotalCost" class="control-title"></label>
                    <input asp-for="TotalCost" class="form-control-s" />
                    <span asp-validation-for="TotalCost" class="text-danger"></span>
                </div>
            </div>
        </div>
        <div id="pnlSIGN" class="row">
            <div class=form-inline>
                <div class="form-group">
                    <label asp-for="SignNo" class="control-title"></label>
                    <input asp-for="SignNo" class="form-control" style="text-transform:uppercase;" />
                    <span asp-validation-for="SignNo" class="text-danger"></span>
                </div>
            </div>
        </div>
        <div id="pnlACCDATE" class="row">
            <div class=form-inline>
                <div class="form-group">
                    <label asp-for="AccountDate" class="control-title"></label>
                    <input asp-for="AccountDate" class="form-control" />
                    <span asp-validation-for="AccountDate" class="text-danger"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div style="padding-left: 115px">
                <input type="submit" value="儲存" class="btn btn-default" />
            </div>
        </div>

    </div>
</form>

<!-- 廠商 Modal -->
<div id="modalVENDOR" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content" style="background-color: #1D3C4C">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" style="color:#fff">&times;</button>
                <h4 class="modal-title">選擇廠商</h4>
            </div>
            <div id="pnlSELECTVENDOR" class="modal-body">
                @await Component.InvokeAsync("QryVendor")
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">儲存</button>
            </div>
        </div>
    </div>
</div>