EDIS/EDIS/Controllers/RepairSearchController.cs
using EDIS.Data;
using EDIS.Models.RepairModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EDIS.Controllers
{
    [Authorize]
    public class RepairSearchController : Controller
    {
        private readonly ApplicationDbContext _context;

        public RepairSearchController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: RepairSearch/
        public IActionResult Index()
        {
            List<SelectListItem> FlowlistItem = new List<SelectListItem>();
            FlowlistItem.Add(new SelectListItem { Text = "未結案", Value = "未結案" });
            FlowlistItem.Add(new SelectListItem { Text = "已結案", Value = "已結案" });
            ViewData["FLOWTYPE"] = new SelectList(FlowlistItem, "Value", "Text");

            /* 成本中心 & 申請部門的下拉選單資料 */
            var dptList = new[] { "K", "P", "C" };  //本院部門
            var departments = _context.Departments.Where(d => dptList.Contains(d.Loc)).ToList();
            List<SelectListItem> listItem = new List<SelectListItem>();
            foreach (var item in departments)
            {
                listItem.Add(new SelectListItem
                {
                    Text = item.Name_C + "(" + item.DptId + ")",    //show DptName(DptId)
                    Value = item.DptId
                });
            }

            ViewData["ACCDPT"] = new SelectList(listItem, "Value", "Text");
            ViewData["APPLYDPT"] = new SelectList(listItem, "Value", "Text");

            /* 處理狀態的下拉選單 */
            var dealStatuses = _context.DealStatuses.ToList();
            List<SelectListItem> listItem2 = new List<SelectListItem>();
            foreach (var item in dealStatuses)
            {
                listItem2.Add(new SelectListItem
                {
                    Text = item.Title,
                    Value = item.Id.ToString()
                });
            }
            ViewData["DealStatus"] = new SelectList(listItem2, "Value", "Text");

            /* 有無費用 的下拉選單 */
            List<SelectListItem> listItem3 = new List<SelectListItem>();
            listItem3.Add(new SelectListItem { Text = "有", Value = "Y" });
            listItem3.Add(new SelectListItem { Text = "無", Value = "N" });
            ViewData["IsCharged"] = new SelectList(listItem3, "Value", "Text");

            /* 處理日期查詢的下拉選單 */
            List<SelectListItem> listItem4 = new List<SelectListItem>();
            listItem4.Add(new SelectListItem { Text = "申請日", Value = "申請日" });
            listItem4.Add(new SelectListItem { Text = "完工日", Value = "完工日" });
            listItem4.Add(new SelectListItem { Text = "結案日", Value = "結案日" });
            ViewData["DateType"] = new SelectList(listItem4, "Value", "Text", "申請日");

            /* 請修類別 的下拉選單 */
            List<SelectListItem> listItem5 = new List<SelectListItem>();
            listItem5.Add(new SelectListItem { Text = "請修", Value = "請修" });
            listItem5.Add(new SelectListItem { Text = "送修", Value = "送修" });
            listItem5.Add(new SelectListItem { Text = "增設", Value = "增設" });
            listItem5.Add(new SelectListItem { Text = "借物", Value = "借物" });
            ViewData["qtyRepType"] = new SelectList(listItem5, "Value", "Text");

            QryRepListData data = new QryRepListData();

            return View(data);
        }

        // POST: RepairSearch/GetQueryList
        [HttpPost]
        public ActionResult GetQueryList(QryRepListData qdata)
        {
            string docid = qdata.qtyDOCID;
            string ano = qdata.qtyASSETNO;
            string acc = qdata.qtyACCDPT;
            string aname = qdata.qtyASSETNAME;
            string ftype = qdata.qtyFLOWTYPE;
            string dptid = qdata.qtyDPTID;
            string qtyDate1 = qdata.qtyApplyDateFrom;
            string qtyDate2 = qdata.qtyApplyDateTo;
            string qtyDealStatus = qdata.qtyDealStatus;
            string qtyIsCharged = qdata.qtyIsCharged;
            string qtyDateType = qdata.qtyDateType;
            string qtyRepType = qdata.qtyRepType;
            string qtyTroubleDes = qdata.qtyTroubleDes;

            DateTime applyDateFrom = DateTime.Now;
            DateTime applyDateTo = DateTime.Now;
            /* Dealing search by date. */
            if (qtyDate1 != null && qtyDate2 != null)// If 2 date inputs have been insert, compare 2 dates.
            {
                DateTime date1 = DateTime.Parse(qtyDate1);
                DateTime date2 = DateTime.Parse(qtyDate2);
                int result = DateTime.Compare(date1, date2);
                if (result < 0)
                {
                    applyDateFrom = date1.Date;
                    applyDateTo = date2.Date;
                }
                else if (result == 0)
                {
                    applyDateFrom = date1.Date;
                    applyDateTo = date1.Date;
                }
                else
                {
                    applyDateFrom = date2.Date;
                    applyDateTo = date1.Date;
                }
            }
            else if (qtyDate1 == null && qtyDate2 != null)
            {
                applyDateFrom = DateTime.Parse(qtyDate2);
                applyDateTo = DateTime.Parse(qtyDate2);
            }
            else if (qtyDate1 != null && qtyDate2 == null)
            {
                applyDateFrom = DateTime.Parse(qtyDate1);
                applyDateTo = DateTime.Parse(qtyDate1);
            }


            List<RepairSearchListVModel> rv = new List<RepairSearchListVModel>();

            /* Querying data. */
            var rps = _context.Repairs.AsQueryable();
            var repairFlows = _context.RepairFlows.AsQueryable();
            var repairDtls = _context.RepairDtls.AsQueryable();
            if (!string.IsNullOrEmpty(docid))   //表單編號
            {
                docid = docid.Trim();
                rps = rps.Where(v => v.DocId == docid);
            }
            if (!string.IsNullOrEmpty(ano))     //財產編號
            {
                rps = rps.Where(v => v.AssetNo == ano);
            }
            if (!string.IsNullOrEmpty(dptid))   //所屬部門編號
            {
                rps = rps.Where(v => v.DptId == dptid);
            }
            if (!string.IsNullOrEmpty(acc))     //成本中心
            {
                rps = rps.Where(v => v.AccDpt == acc);
            }
            if (!string.IsNullOrEmpty(aname))   //物品名稱(關鍵字)
            {
                rps = rps.Where(v => v.AssetName != null)
                         .Where(v => v.AssetName.Contains(aname));
            }
            if (!string.IsNullOrEmpty(qtyRepType))  //請修類別
            {
                rps = rps.Where(v => v.RepType == qtyRepType);
            }
            if (!string.IsNullOrEmpty(qtyTroubleDes))   //錯誤描述(關鍵字)
            {
                rps = rps.Where(v => v.TroubleDes.Contains(qtyTroubleDes));
            }
            if (string.IsNullOrEmpty(qtyDate1) == false || string.IsNullOrEmpty(qtyDate2) == false)  //申請日
            {
                if (qtyDateType == "申請日")
                {
                    rps = rps.Where(v => v.ApplyDate >= applyDateFrom && v.ApplyDate <= applyDateTo);
                }
            }
            if (!string.IsNullOrEmpty(ftype))   //流程狀態
            {
                switch(ftype)
                {
                    case "未結案":
                        repairFlows = repairFlows.Where(f => f.Status == "?");
                        break;
                    case "已結案":
                        repairFlows = repairFlows.Where(f => f.Status == "2");
                        break;
                }
            }
            else
            {
                repairFlows = repairFlows.Where(f => f.Status == "2" || f.Status == "?");
            }
            if (!string.IsNullOrEmpty(qtyDealStatus))   //處理狀態
            {
                repairDtls = repairDtls.Where(r => r.DealState == Convert.ToInt32(qtyDealStatus));
            }
            /* Search IsCharged. */
            if (!string.IsNullOrEmpty(qtyIsCharged))    //有無費用
            {
                repairDtls = repairDtls.Where(r => r.IsCharged == qtyIsCharged);
            }

            /* If no search result. */
            if (rps.Count() == 0)
            {
                return View("SearchList", rv);
            }

            rps.Join(repairFlows, r => r.DocId, f => f.DocId,
                (r, f) => new
                {
                    repair = r,
                    flow = f
                })
                .Join(repairDtls, m => m.repair.DocId, d => d.DocId,
                (m, d) => new
                {
                    repair = m.repair,
                    flow = m.flow,
                    repdtl = d
                })
                .Join(_context.Departments, j => j.repair.AccDpt, d => d.DptId,
                (j, d) => new
                {
                    repair = j.repair,
                    flow = j.flow,
                    repdtl = j.repdtl,
                    dpt = d
                })
                .ToList()
                .ForEach(j => rv.Add(new RepairSearchListVModel
                {
                    DocType = "請修",
                    RepType = j.repair.RepType,
                    DocId = j.repair.DocId,
                    ApplyDate = j.repair.ApplyDate,
                    PlaceLoc = j.repair.LocType,
                    ApplyDpt = j.repair.DptId,
                    AccDpt = j.repair.AccDpt,
                    AccDptName = j.dpt.Name_C,
                    TroubleDes = j.repair.TroubleDes,
                    DealState = _context.DealStatuses.Find(j.repdtl.DealState).Title,
                    DealDes = j.repdtl.DealDes,
                    Cost = j.repdtl.Cost,
                    Days = DateTime.Now.Subtract(j.repair.ApplyDate).Days,

EDIS/EDIS/Views/RepairSearch/Index.cshtml
@model EDIS.Models.RepairModels.QryRepListData

@{
    Layout = "~/Views/Shared/_PassedLayout.cshtml";
    ViewData["Title"] = "Search";
}

<link href="~/css/bootstrap-combobox.css" rel="stylesheet" />
<script src="~/js/bootstrap-combobox.js"></script>

<script type="text/javascript">
    $(document).ready(function () {
        $('.combobox').combobox();
        /* While loading this page, default search repairDocs. */
        $("#repSearchForm").submit(function () {
            if ($("#qtyDOCID").val() === "" && $("#qtyASSETNO").val() === "" && $("#qtyACCDPT").val() === "" &&
                $("#qtyASSETNAME").val() === "" && $("#qtyFLOWTYPE").val() === "" && $("#qtyDPTID").val() === "" &&
                $("#qtyDealStatus").val() === "" && $("#qtyIsCharged").val() === "" && $("#qtyTroubleDes").val() === "" &&
                $("#qtyRepType").val() === "" && $("#qtyApplyDateFrom").val() === "" && $("#qtyApplyDateTo").val() === "") {
                alert("至少選擇一個搜尋條件!");
                return false;
            }
            return true;
        });
    });
</script>

<h3>請修單查詢</h3>
<hr />

<form asp-controller="RepairSearch" asp-action="GetQueryList" asp-area="" data-ajax="true"
    data-ajax-update="#pnlREPLIST" data-ajax-method="POST" id="repSearchForm"
    data-ajax-begin="$.Toast.showToast({
      'title':'查詢中，請稍待...',
      'icon':'loading',
      'duration':0
      })"
    data-ajax-complete="$.Toast.hideToast()">

    <h4>查詢條件 - 全院案件</h4>

    <div class="container">
        <div class="row">
            <div class=form-inline>
                <div class="form-group">
                    <label for="qtyDOCID" class="control-title">表單編號</label>
                    <input asp-for="qtyDOCID" class="form-control" />
                </div>
                <div class="form-group">
                    <label for="qtyASSETNO" class="control-title">財產編號</label>
                    <input asp-for="qtyASSETNO" class="form-control-s" />
                </div>
                <div class="form-group">
                    <label for="qtyACCDPT" class="control-title">成本中心</label>
                    <select asp-for="qtyACCDPT" asp-items="@ViewData["ACCDPT"] as SelectList" class="form-control combobox">
                        <option value="">請選擇</option>
                    </select>
                </div>
            </div>
        </div>
        <div class="row">
            <div class=form-inline>
                <div class="form-group">
                    <label for="qtyASSETNAME" class="control-title">物品名稱<br />(關鍵字)</label>
                    <input asp-for="qtyASSETNAME" class="form-control" />
                </div>
                <div class="form-group">
                    <label for="qtyFLOWTYPE" class="control-title">流程狀態</label>
                    <select asp-for="qtyFLOWTYPE" asp-items="@ViewData["FLOWTYPE"] as SelectList" class="form-control-s">
                        <option value="">請選擇</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="qtyDPTID" class="control-title">申請部門</label>
                    <select asp-for="qtyDPTID" asp-items="@ViewData["APPLYDPT"] as SelectList" class="form-control combobox">
                        <option value="">請選擇</option>
                    </select>
                </div>
            </div>
        </div>
        <div class="row">
            <div class=form-inline>
                <div class="form-group">
                    <label for="qtyDealStatus" class="control-title">處理狀態</label>
                    <select asp-for="qtyDealStatus" asp-items="@ViewData["DealStatus"] as SelectList" class="form-control">
                        <option value="">請選擇</option>
                    </select>
                </div>
                <label for="qtyIsCharged" class="control-title">[有][無]費用</label>
                <select asp-for="qtyIsCharged" asp-items="@ViewData["IsCharged"] as SelectList" class="form-control-s">
                    <option value="">請選擇</option>
                </select>
                <div class="form-group">
                    <label for="qtyTroubleDes" class="control-title">故障描述<br />(關鍵字)</label>
                    <input asp-for="qtyTroubleDes" class="form-control" />
                </div>
            </div>
        </div>
        <div class="row">
            <div class=form-inline>
                <div class="form-group">
                    <label for="qtyRepType" class="control-title">請修類別</label>
                    <select asp-for="qtyRepType" asp-items="@ViewData["qtyRepType"] as SelectList" class="form-control">
                        <option value="">請選擇</option>
                    </select>
                </div>
            </div>
        </div>
        <div class="row">
            <div class=form-inline>
                <div class="form-group">
                    <label for="qtyApplyDateFrom" class="control-title">日期查詢</label>
                    <span>
                        <select asp-for="qtyDateType" asp-items="@ViewData["DateType"] as SelectList" class="form-control-s"></select>
                    </span>
                    <input asp-for="qtyApplyDateFrom" class="form-control" />
                    <span> ~ </span>
                    <input asp-for="qtyApplyDateTo" class="form-control" />
                </div>
            </div>
        </div>
        <div class="row">
            <div class=form-inline>
                <div class="form-group">
                    <div style="margin-left:115px">
                        <input id="btnQTY" type="submit" value="查詢" class="btn btn-default" />
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

<div id="pnlREPLIST"></div>

EDIS/EDIS/Views/RepairSearch/SearchList.cshtml
@model IEnumerable<EDIS.Models.RepairModels.RepairSearchListVModel>
@using System.Security.Claims
@using Microsoft.AspNetCore.Identity
@using EDIS.Models.Identity

@inject CustomUserManager UserManager
@{
    Layout = null;
}
<style>
    td a {
        color: deepskyblue;
    }
</style>
@if (Model.Count() <= 0)
{
    <p class="text-danger">無任何資料!</p>

}
else
{
    <table class="table" style="width: 100%">
        <tr>
            <th></th>
            <th>
                @Html.DisplayNameFor(model => model.RepType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DocId)<br />
                @Html.DisplayNameFor(model => model.ApplyDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AccDptName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AssetName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PlaceLoc)
            </th>
            <th style="width: 300px;">
                @Html.DisplayNameFor(model => model.TroubleDes)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DealState)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DealDes)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cost)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Days)
            </th>
            <th>
                文件狀態
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FlowUidName)
            </th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td width="100px">
                    @Html.ActionLink("預覽", "Views", "Repair", new { Area = "", id = item.DocId }, new { target = "_blank" })
                    @Html.Raw(" |")
                    @Html.ActionLink("列印", "PrintRepairDoc", "Repair", new { Area = "", DocId = item.DocId }, new { target = "_blank" })
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.RepType)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DocId)<br />
                    @Html.DisplayFor(modelItem => item.ApplyDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AccDptName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AssetNo)<br />
                    @Html.DisplayFor(modelItem => item.AssetName)<br />
                    @Html.DisplayFor(modelItem => item.Brand)<br />
                    @Html.DisplayFor(modelItem => item.Type)<br />

                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PlaceLoc)
                </td>
                <td style="max-width:450px; word-wrap: break-word;">
                    @Html.DisplayFor(modelItem => item.TroubleDes)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DealState)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DealDes)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Cost)
                </td>
                <td>
                    @if (item.Flg != "2")
                    {
                        @Html.DisplayFor(modelItem => item.Days)
                    }
                </td>
                <td>
                    @if (item.Flg == "2")
                    {
                        <span>已結案</span>
                    }
                    else
                    {
                        <span>未結案</span>
                    }
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FlowUidName)
                </td>
            </tr>
        }

    </table>
}