EDIS/EDIS/Components/AssetKeep/AssetKeepEditViewComponent.cs
using EDIS.Data;
using EDIS.Models.Identity;
using EDIS.Models.KeepModels;
using EDIS.Repositories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EDIS.Components.AssetKeep
{
    public class AssetKeepEditViewComponent : ViewComponent
    {
        private readonly ApplicationDbContext _context;
        private readonly IRepository<AppUserModel, int> _userRepo;
        private readonly CustomUserManager userManager;
        private readonly CustomRoleManager roleManager;

        public AssetKeepEditViewComponent(ApplicationDbContext context,
                                          IRepository<AppUserModel, int> userRepo,
                                          CustomUserManager customUserManager,
                                          CustomRoleManager customRoleManager)
        {
            _context = context;
            _userRepo = userRepo;
            userManager = customUserManager;
            roleManager = customRoleManager;
        }

        public async Task<IViewComponentResult> InvokeAsync(string id, string viewType = null)
        {
            if (viewType == "Details")
            {
                if (id == null)
                {
                    return Content("無資料!");  
                }
                AssetKeepModel assetKeep = _context.AssetKeeps.Find(id);
                if (assetKeep == null)
                {
                    return Content("無資料!");
                }
                assetKeep.KeepEngName = assetKeep.KeepEngId == 0 ? "" : _context.AppUsers.Find(assetKeep.KeepEngId).FullName;
                return View("Details", assetKeep);
            }
            else
            {
                List<SelectListItem> listItem = new List<SelectListItem>();
                AppUserModel u;
                //db.AppUsers.ToList().ForEach(d =>
                //{
                //    listItem.Add(new SelectListItem { Text = d.FullName, Value = d.Id.ToString() });
                //});

                // Get MedEngineers to set dropdownlist.
                var s = roleManager.GetUsersInRole("RepEngineer").ToList();
                foreach (string l in s)
                {
                    u = _context.AppUsers.Where(ur => ur.UserName == l).FirstOrDefault();
                    if (u != null)
                    {
                        listItem.Add(new SelectListItem { Text = u.FullName, Value = u.Id.ToString() });
                    }
                }
                ViewData["KeepEngId"] = new SelectList(listItem, "Value", "Text");

                List<SelectListItem> listItem2 = new List<SelectListItem>();
                listItem2.Add(new SelectListItem { Text = "自行", Value = "自行" });
                listItem2.Add(new SelectListItem { Text = "委外", Value = "委外" });
                listItem2.Add(new SelectListItem { Text = "保固", Value = "保固" });
                listItem2.Add(new SelectListItem { Text = "租賃", Value = "租賃" });
                ViewData["InOut"] = new SelectList(listItem2, "Value", "Text", "");
                //
                List<SelectListItem> listItem3 = new List<SelectListItem>();
                _context.KeepFormats.ToList()
                    .ForEach(x =>
                    {
                        listItem3.Add(new SelectListItem { Text = x.FormatId + "(" + x.Plants + ")", Value = x.FormatId });
                    });
                ViewData["FormatId"] = new SelectList(listItem3, "Value", "Text", "");
                //
                if (id == null)
                {
                    return View();
                }
                AssetKeepModel assetKeep = _context.AssetKeeps.Find(id);
                if (assetKeep == null)
                {
                    assetKeep = new AssetKeepModel();
                    assetKeep.DeviceNo = id;
                }
                return View(assetKeep);
            }
        }
    }
}

EDIS/EDIS/Controllers/AssetKeepController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Encodings.Web;
using System.Threading.Tasks;
using EDIS.Data;
using EDIS.Models.KeepModels;
using EDIS.Models.Identity;
using EDIS.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace EDIS.Controllers
{
    [Authorize]
    public class AssetKeepController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly CustomUserManager userManager;
        private readonly CustomRoleManager roleManager;

        public AssetKeepController(ApplicationDbContext context,
                                   CustomRoleManager customRoleManager,
                                   CustomUserManager customUserManager)
        {
            _context = context;
            roleManager = customRoleManager;
            userManager = customUserManager;
        }

        // GET: AssetKeep
        public IActionResult Index()
        {
            return View();
        }

        // GET: AssetKeep/Details/5
        public IActionResult Details(string id)
        {
            if (id == null)
            {
                return BadRequest();
            }
            AssetKeepModel assetKeep = _context.AssetKeeps.Find(id);
            if (assetKeep == null)
            {
                return StatusCode(404);
            }
            assetKeep.KeepEngName = assetKeep.KeepEngId == 0 ? "" : _context.AppUsers.Find(assetKeep.KeepEngId).FullName;
            return PartialView(assetKeep);
        }

        // GET: AssetKeep/Edit/5
        public IActionResult Edit(string id)
        {
            List<SelectListItem> listItem = new List<SelectListItem>();
            AppUserModel u;
            //db.AppUsers.ToList().ForEach(d =>
            //{
            //    listItem.Add(new SelectListItem { Text = d.FullName, Value = d.Id.ToString() });
            //});

            // Get MedEngineers to set dropdownlist.
            var s = roleManager.GetUsersInRole("RepEngineer").ToList();
            foreach (string l in s)
            {
                u = _context.AppUsers.Where(ur => ur.UserName == l).FirstOrDefault();
                if (u != null)
                {
                    listItem.Add(new SelectListItem { Text = u.FullName, Value = u.Id.ToString() });
                }
            }
            ViewData["KeepEngId"] = new SelectList(listItem, "Value", "Text", "");

            List<SelectListItem> listItem2 = new List<SelectListItem>();
            listItem2.Add(new SelectListItem { Text = "自行", Value = "自行" });
            listItem2.Add(new SelectListItem { Text = "委外", Value = "委外" });
            listItem2.Add(new SelectListItem { Text = "保固", Value = "保固" });
            listItem2.Add(new SelectListItem { Text = "租賃", Value = "租賃" });
            ViewData["InOut"] = new SelectList(listItem2, "Value", "Text", "");
            //
            List<SelectListItem> listItem3 = new List<SelectListItem>();
            _context.KeepFormats.ToList()
                .ForEach(x =>
                {
                    listItem3.Add(new SelectListItem { Text = x.FormatId, Value = x.FormatId });
                });
            ViewData["FormatId"] = new SelectList(listItem3, "Value", "Text", "");
            //
            if (id == null)
            {
                return PartialView();
            }
            AssetKeepModel assetKeep = _context.AssetKeeps.Find(id);
            if (assetKeep == null)
            {
                assetKeep = new AssetKeepModel();
                assetKeep.AssetNo = id;
            }
            return PartialView(assetKeep);
        }

        // POST: AssetKeep/Edit/5
        [HttpPost]
        public IActionResult Edit(AssetKeepModel assetKeep)
        {
            if (ModelState.IsValid)
            {
                assetKeep.KeepEngName = _context.AppUsers.Find(assetKeep.KeepEngId).FullName;
                _context.Entry(assetKeep).State = EntityState.Modified;
                _context.SaveChanges();
                return new JsonResult(assetKeep)
                {
                    Value = new { success = true, error = "" }
                };
            }
            else
            {
                string msg = "";
                foreach (var error in ViewData.ModelState.Values.SelectMany(modelState => modelState.Errors))
                {
                    msg += error.ErrorMessage + Environment.NewLine;
                }
                throw new Exception(msg);
            }
        }

        // POST: AssetKeep/UpdEngineer/5
        [HttpPost]
        public ActionResult UpdEngineer(string id, string assets)
        {
            string[] s = assets.Split(new char[] { ';' });
            AssetKeepModel assetKeep;
            foreach (string ss in s)
            {
                assetKeep = _context.AssetKeeps.Find(ss);
                if (assetKeep != null)
                {
                    AppUserModel u = _context.AppUsers.Find(Convert.ToInt32(id));
                    if (u != null)
                    {
                        assetKeep.KeepEngId = u.Id;
                        assetKeep.KeepEngName = u.FullName;
                        _context.Entry(assetKeep).State = EntityState.Modified;
                        _context.SaveChanges();
                    }
                }
            }
            return new JsonResult(id)
            {
                Value = new { success = true, error = "" }
            };
        }

    }
}

EDIS/EDIS/Views/AssetKeep/Details.cshtml
@model EDIS.Models.KeepModels.AssetKeepModel

<div class="form-horizontal">
    <h4>設備保養資料</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.ContractNo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.ContractNo, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ContractNo, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Cycle, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.Cycle, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Cycle, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.KeepYm, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.KeepYm, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.KeepYm, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.KeepYm2, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.KeepYm2, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.KeepYm2, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.KeepEngId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.KeepEngName, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Cost, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.Cost, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Cost, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Hours, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.Hours, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Hours, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.InOut, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.InOut, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.FormatId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.FormatId, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.FormatId, "", new { @class = "text-danger" })
        </div>
    </div>
</div>

EDIS/EDIS/Views/AssetKeep/Edit.cshtml
@model EDIS.Models.KeepModels.AssetKeepModel
@{
    Layout = "~/Views/Shared/_PassedLayout.cshtml";
}
<link href="~/css/bootstrap-combobox.css" rel="stylesheet" />
<script src="~/js/bootstrap-combobox.js"></script>

<script>
    $(function () {
        $(".assetKeepCombobox").combobox();
    });
</script>

<form asp-action="Edit" asp-controller="AssetKeep" asp-area="" data-ajax="true" data-ajax-method="POST"
      data-ajax-begin="$.Toast.showToast({
      'title':'作業進行中，請稍待...',
      'icon':'loading',
      'duration':0
      })"
      data-ajax-complete="$.Toast.hideToast()"
      data-ajax-success="showmsg">

    <div class="form-horizontal">
        <h4>設備保養資料</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input asp-for="AssetNo" type="hidden" id="AssetNo2" />

        <div class="form-group">
            <label asp-for="ContractNo" class="control-label col-md-2"></label>
            <div class="col-md-10">
                <input asp-for="ContractNo" class="form-control" />
                <span asp-validation-for="ContractNo" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="Cycle" class="control-label col-md-2"></label>
            <div class="col-md-10">
                <input asp-for="Cycle" class="form-control" />
                <span asp-validation-for="Cycle" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="KeepYm" class="control-label col-md-2"></label>
            <div class="col-md-10">
                <input asp-for="KeepYm" class="form-control" />
                <span asp-validation-for="KeepYm" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="KeepYm2" class="control-label col-md-2"></label>
            <div class="col-md-10">
                <input asp-for="KeepYm2" class="form-control" />
                <span asp-validation-for="KeepYm2" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="KeepEngId" class="control-label col-md-2"></label>
            <div class="col-md-10">
                <select asp-for="KeepEngId" asp-items="@ViewData["KeepEngId"] as SelectList" class="form-control-s">
                    <option disabled selected>請選擇</option>
                </select>
                <span asp-validation-for="KeepEngId" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="Cost" class="control-label col-md-2"></label>
            <div class="col-md-10">
                <input asp-for="Cost" class="form-control" />
                <span asp-validation-for="Cost" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="Hours" class="control-label col-md-2"></label>
            <div class="col-md-10">
                <input asp-for="Hours" class="form-control" />
                <span asp-validation-for="Hours" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="InOut" class="control-label col-md-2"></label>
            <div class="col-md-10">
                <select asp-for="InOut" asp-items="@ViewData["InOut"] as SelectList" class="form-control-s">
                    <option disabled selected>請選擇</option>
                </select>
                <span asp-validation-for="InOut" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="FormatId" class="control-label col-md-2"></label>
            <div class="col-md-10">
                <select asp-for="FormatId" asp-items="@ViewData["FormatId"] as SelectList" class="form-control-s assetKeepCombobox">
                    <option disabled selected>請選擇</option>
                </select>
                <span asp-validation-for="FormatId" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="儲存" class="btn btn-default" />
            </div>
        </div>
    </div>

</form>